version: "3.8"

services:
  # Courses and Topics Service
  courses_topics:
    build:
      context: ./backend
      dockerfile: courses_topics/Dockerfile
    ports:
      - "8080:8080" # FastAPI Server
      - "50051:50051" # gRPC Server
    environment:
      - PYTHONPATH=/app
      - POSTGRES_URL=postgresql://postgres:password@host.docker.internal:5432/courseDB
      - MONGO_URL=mongodb://host.docker.internal:27017
      - MONGO_DB_NAME=expanseDB
    volumes:
      - ./backend/common:/app/common
      - ./backend/protos:/app/protos
      - ./backend/courses_topics:/app/courses_topics
    container_name: courses_topics
    restart: always

  # Quiz Service
  quiz_service:
    build:
      context: ./backend
      dockerfile: quiz_service/Dockerfile
    ports:
      - "8082:8082" # FastAPI Server
    environment:
      - PYTHONPATH=/app
      - POSTGRES_URL=postgresql://postgres:password@host.docker.internal:5432/quizDB
      - MONGO_URL=mongodb://host.docker.internal:27017
      - MONGO_DB_NAME=expanseDB
      - GRPC_SERVER=courses_topics:50051
    volumes:
      - ./backend/common:/app/common
      - ./backend/protos:/app/protos
      - ./backend/quiz_service:/app/quiz_service
    container_name: quiz_service
    restart: always

  # Discussion Service
  discussion_forum:
    build:
      context: ./backend
      dockerfile: discussion_forum/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - PYTHONPATH=/app
      - POSTGRES_URL=postgresql://postgres:password@host.docker.internal:5432/forumDB
      - MONGO_URL=mongodb://host.docker.internal:27017
      - MONGO_DB_NAME=expanseDB
      - GRPC_SERVER=courses_topics:50051
    volumes:
      - ./backend/common:/app/common
      - ./backend/protos:/app/protos
      - ./backend/discussion_forum:/app/discussion_forum
    container_name: discussion_forum
    restart: always

  # Frontend and Authentication Service
  frontend-with-auth:
    build:
      context: ./frontend-with-auth
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./frontend-with-auth/.env
    volumes:
      - ./frontend-with-auth:/app:delegated
    command: npm run dev
    container_name: frontend-and-auth
    restart: always
