# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: check_enrollment.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'check_enrollment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x63heck_enrollment.proto\x12\x0e\x63ourses_topics\"7\n\x11\x45nrollmentRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x11\n\tcourse_id\x18\x02 \x01(\x05\")\n\x12\x45nrollmentResponse\x12\x13\n\x0bis_enrolled\x18\x01 \x01(\x08\x32m\n\x11\x45nrollmentService\x12X\n\x0f\x43heckEnrollment\x12!.courses_topics.EnrollmentRequest\x1a\".courses_topics.EnrollmentResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'check_enrollment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENROLLMENTREQUEST']._serialized_start=42
  _globals['_ENROLLMENTREQUEST']._serialized_end=97
  _globals['_ENROLLMENTRESPONSE']._serialized_start=99
  _globals['_ENROLLMENTRESPONSE']._serialized_end=140
  _globals['_ENROLLMENTSERVICE']._serialized_start=142
  _globals['_ENROLLMENTSERVICE']._serialized_end=251
# @@protoc_insertion_point(module_scope)
