apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: discussion-forum-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: discussion-forum
  minReplicas: 2
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 40
