apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  NEXTAUTH_URL: "http://localhost:3000"
  DATABASE_URL: "postgresql://postgres:password@host.docker.internal:5432/expanse"
