apiVersion: v1
kind: Secret
metadata:
  name: frontend-secrets
type: Opaque
data:
  NEXTAUTH_SECRET: c2tRUVMvbzFKemF4V0FSd1c2OHE2RnBJbi8xQXB0Zm5ORGpQMzBRRlo1ST0=
  GOOGLE_CLIENT_ID: ODcyOTE4MTQ0ODkxLTcwNjVnMXB2bGMya2hwN2U4MjYwc3BtMnJhazkyMGJqLmFwcHMuZ29vZ2xlYXV0aC5jb20=
  GOOGLE_CLIENT_SECRET: YmFzZTY0LWVuY29kZWQtZ29vZ2xlLWNsaWVudC1zZWNyZXQ=