apiVersion: apps/v1
kind: Deployment
metadata:
  name: courses-topics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: courses-topics
  template:
    metadata:
      labels:
        app: courses-topics
    spec:
      containers:
      - name: courses-topics
        image: abshark/expanse-courses  # Replace with your built Docker image
        ports:
          - containerPort: 8080  # REST API
          - containerPort: 50051 # gRPC
        envFrom:
          - configMapRef:
              name: backend-config
          - configMapRef:
              name: course-config
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "128Mi"
