apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-and-auth
  labels:
    app: frontend-and-auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-and-auth
  template:
    metadata:
      labels:
        app: frontend-and-auth
    spec:
      containers:
        - name: frontend-and-auth-container
          image: abshark/expanse-frontend-and-auth
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: frontend-config
            - secretRef:
                name: frontend-secrets
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
