apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quiz-service
  template:
    metadata:
      labels:
        app: quiz-service
    spec:
      containers:
      - name: quiz-service
        image: abshark/expanse-quiz  # Replace with your built Docker image
        ports:
          - containerPort: 8082
        envFrom:
          - configMapRef:
              name: backend-config
          - configMapRef:
              name: quiz-config
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "128Mi"