import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./NavBar";
import { Providers } from "./components/provider";
import AuthProvider from "./auth/Provider";
import { Container } from "@chakra-ui/react";

export const metadata: Metadata = {
  title: "Expanse",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <AuthProvider>
          <Providers>
            <nav>
              <NavBar />
            </nav>
            <Container>
              <main className="mt-20">{children}</main>
            </Container>
          </Providers>
        </AuthProvider>
      </body>
    </html>
  );
}
